import type { Metadata } from 'next';
import dynamic from 'next/dynamic';
import { DM_Sans } from 'next/font/google';
import './globals.css';

const NavBar = dynamic(() => import('../components/NavBar/NavBar'));

const dmSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin'],
  display: 'swap',
  fallback: ['Arial', 'sans-serif'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='overflow-x-hidden' suppressHydrationWarning>
      <body className={`${dmSans.variable} overflow-x-hidden antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
